FROM node:22-alpine AS base
RUN corepack enable && corepack prepare pnpm@9 --activate

FROM base AS development-dependencies-env
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

FROM base AS dev-env
COPY . /app
COPY --from=development-dependencies-env /app/node_modules /app/node_modules
WORKDIR /app
ENV PORT=5174
EXPOSE 5174
CMD ["pnpm", "run", "dev"]